#!/bin/sh

. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase
log.*
rm -rf solutionMonitoring/*.png

rm -rf history

clear
#------------------------------------------------------------------------------
