#!/bin/sh

#------------------------------------------------------------------------------
clear
./Allclean
blockMesh
decomposePar
# python3 $FOAM_SRC/solutionMonitoring/probesMonitoring.py & time ehdFoam_b0R7
mpirun -np 8 ehdFoam_b0R7 -parallel
#> 
#python3 $solutionMonitoring/probesMonitoring.py & time ehdFoam_b0R7
#------------------------------------------------------------------------------
